// Seed script to populate diverse articles for all article types
// This creates articles for user ID 3 (Lê Văn C) to show in Reporter Portal

import * as kv from "./kv_store.tsx";

export async function seedArticles() {
  const sampleArticles = [
    // NEWS ARTICLES (User 3)
    {
      id: 1,
      title: 'Công nghệ AI đang thay đổi thế giới',
      type: 'news',
      status: 'published',
      category: 'Thời sự',
      categories: ['Thời sự'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 5432,
      comments: 87,
      publishDate: '2024-12-20 10:30:00',
      updatedDate: '2024-12-20 14:20:00',
      thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=250&fit=crop',
      excerpt: 'Phân tích về tác động của AI trong các ngành công nghiệp hiện đại',
      content: '<p>AI đang tạo ra những thay đổi lớn trong cách chúng ta sống và làm việc.</p>',
      featured: true,
      wordCount: 1500,
      slug: 'thoi-su/cong-nghe-ai-dang-thay-doi-the-gioi',
      tags: ['AI', 'Công nghệ', 'Tương lai'],
    },
    {
      id: 2,
      title: 'Thị trường chứng khoán tăng điểm mạnh',
      type: 'news',
      status: 'published',
      category: 'Kinh tế',
      categories: ['Kinh tế'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 3210,
      comments: 45,
      publishDate: '2024-12-22 09:00:00',
      updatedDate: '2024-12-22 09:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=250&fit=crop',
      excerpt: 'VN-Index tăng hơn 20 điểm trong phiên giao dịch sáng nay',
      content: '<p>Thị trường chứng khoán Việt Nam ghi nhận phiên tăng điểm mạnh mẽ.</p>',
      wordCount: 1200,
      slug: 'kinh-te/thi-truong-chung-khoan-tang-diem-manh',
      tags: ['Chứng khoán', 'VN-Index', 'Kinh tế'],
    },
    {
      id: 3,
      title: 'Lễ hội văn hóa truyền thống thu hút hàng nghìn người',
      type: 'news',
      status: 'draft',
      category: 'Văn hóa',
      categories: ['Văn hóa'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 234,
      comments: 5,
      publishDate: '2024-12-28 14:00:00',
      updatedDate: '2024-12-28 16:30:00',
      thumbnail: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=250&fit=crop',
      excerpt: 'Sự kiện văn hóa lớn nhất năm với nhiều hoạt động đặc sắc',
      content: '<p>Lễ hội đã diễn ra trong không khí sôi động và đầm ấm.</p>',
      wordCount: 980,
      slug: 'van-hoa/le-hoi-van-hoa-truyen-thong',
      tags: ['Văn hóa', 'Lễ hội', 'Truyền thống'],
    },

    // VIDEO ARTICLES (User 3)
    {
      id: 4,
      title: 'Phóng sự: Cuộc sống nông thôn mới',
      type: 'video',
      status: 'published',
      category: 'Phóng sự',
      categories: ['Phóng sự'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 7890,
      comments: 156,
      publishDate: '2024-12-15 14:00:00',
      updatedDate: '2024-12-15 16:30:00',
      thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=250&fit=crop',
      excerpt: 'Khám phá cuộc sống nông thôn mới tại miền Bắc Việt Nam',
      content: '<p>Phóng sự đặc biệt về chương trình nông thôn mới.</p>',
      slug: 'phong-su/phong-su-cuoc-song-nong-thon-moi',
      tags: ['Phóng sự', 'Nông thôn', 'Video'],
      videoData: {
        sourceType: 'youtube',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        duration: { hours: 0, minutes: 25, seconds: 45 },
        thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=250&fit=crop',
        quality: '1080p',
        summary: 'Phóng sự về cuộc sống nông thôn mới',
      },
    },
    {
      id: 5,
      title: 'Talkshow: Khởi nghiệp trong kỷ nguyên số',
      type: 'video',
      status: 'pending',
      category: 'Talkshow',
      categories: ['Talkshow'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 4321,
      comments: 78,
      publishDate: '2024-12-25 20:00:00',
      updatedDate: '2024-12-25 20:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=400&h=250&fit=crop',
      excerpt: 'Gặp gỡ các founder thành công chia sẻ bí quyết khởi nghiệp',
      content: '<p>Talkshow với sự tham gia của nhiều founder nổi tiếng.</p>',
      slug: 'talkshow/khoi-nghiep-trong-ky-nguyen-so',
      tags: ['Talkshow', 'Khởi nghiệp', 'Startup'],
      videoData: {
        sourceType: 'vimeo',
        url: 'https://vimeo.com/123456789',
        duration: { hours: 1, minutes: 15, seconds: 0 },
        thumbnail: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=400&h=250&fit=crop',
        quality: '4K',
        summary: 'Talkshow về khởi nghiệp',
      },
    },

    // GALLERY ARTICLES (User 3)
    {
      id: 6,
      title: 'Bộ sưu tập ảnh: Hà Nội mùa thu',
      type: 'gallery',
      status: 'published',
      category: 'Du lịch',
      categories: ['Du lịch'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 9876,
      comments: 234,
      publishDate: '2024-12-10 10:00:00',
      updatedDate: '2024-12-10 18:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=400&h=250&fit=crop',
      excerpt: 'Những khoảnh khắc đẹp nhất của Hà Nội vào mùa thu',
      content: '<p>Bộ sưu tập ảnh tuyệt đẹp về Hà Nội mùa thu.</p>',
      slug: 'du-lich/bo-suu-tap-anh-ha-noi-mua-thu',
      tags: ['Du lịch', 'Hà Nội', 'Mùa thu'],
      galleryImages: [
        {
          id: 1,
          url: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=800',
          caption: 'Hồ Gươm buổi sáng',
          alt: 'Hoan Kiem Lake Morning',
          isCover: true,
        },
        {
          id: 2,
          url: 'https://images.unsplash.com/photo-1555469491-0e4f54d7e51b?w=800',
          caption: 'Phố cổ Hà Nội',
          alt: 'Hanoi Old Quarter',
        },
        {
          id: 3,
          url: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800',
          caption: 'Lá vàng rơi',
          alt: 'Falling Leaves',
        },
      ],
    },

    // PODCAST ARTICLES (User 3)
    {
      id: 7,
      title: 'Podcast: Chuyện buổi sáng - Bí quyết làm việc hiệu quả',
      type: 'podcast',
      status: 'published',
      category: 'Chuyện buổi sáng',
      categories: ['Chuyện buổi sáng'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 3456,
      comments: 67,
      publishDate: '2024-12-18 06:00:00',
      updatedDate: '2024-12-18 06:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400&h=250&fit=crop',
      excerpt: 'Chia sẻ những mẹo làm việc hiệu quả từ các chuyên gia',
      content: '<p>Episode đặc biệt với nhiều tips hữu ích.</p>',
      slug: 'podcast/chuyen-buoi-sang-bi-quyet-lam-viec-hieu-qua',
      tags: ['Podcast', 'Productivity', 'Sáng tạo'],
      podcastData: {
        audioUrl: 'https://example.com/podcast-episode-1.mp3',
        duration: { hours: 0, minutes: 45, seconds: 30 },
        episodeNumber: 15,
        seasonNumber: 2,
        hosts: ['Lê Văn C', 'Nguyễn Thị D'],
        guests: ['Chuyên gia A', 'CEO B'],
      },
    },

    // EVENT ARTICLES (User 3)
    {
      id: 8,
      title: 'Hội thảo: Chuyển đổi số trong doanh nghiệp',
      type: 'event',
      status: 'published',
      category: 'Hội thảo',
      categories: ['Hội thảo'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 2345,
      comments: 34,
      publishDate: '2024-12-05 08:00:00',
      updatedDate: '2024-12-05 08:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=250&fit=crop',
      excerpt: 'Sự kiện về chuyển đổi số dành cho doanh nghiệp vừa và nhỏ',
      content: '<p>Hội thảo với sự tham gia của nhiều chuyên gia hàng đầu.</p>',
      slug: 'hoi-thao/chuyen-doi-so-trong-doanh-nghiep',
      tags: ['Sự kiện', 'Chuyển đổi số', 'Doanh nghiệp'],
      eventData: {
        startDate: '2024-12-15 09:00:00',
        endDate: '2024-12-15 17:00:00',
        location: 'Trung tâm Hội nghị Quốc gia, Hà Nội',
        organizer: 'Hiệp hội Chuyển đổi số Việt Nam',
        speakers: ['TS. Nguyễn Văn A', 'CEO Trần Thị B'],
        registrationUrl: 'https://example.com/register',
        capacity: 500,
        registeredCount: 350,
      },
    },

    // BLOG ARTICLES (User 3)
    {
      id: 9,
      title: 'Góc nhìn: Tương lai của Remote Work',
      type: 'blog',
      status: 'published',
      category: 'Góc nhìn',
      categories: ['Góc nhìn'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 1876,
      comments: 56,
      publishDate: '2024-12-12 14:00:00',
      updatedDate: '2024-12-12 14:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400&h=250&fit=crop',
      excerpt: 'Phân tích xu hướng làm việc từ xa trong tương lai',
      content: '<p>Remote work đang thay đổi cách chúng ta làm việc.</p>',
      slug: 'blog/tuong-lai-cua-remote-work',
      tags: ['Blog', 'Remote Work', 'Tương lai'],
    },

    // JOB ARTICLES (User 3)
    {
      id: 10,
      title: 'Tuyển dụng: Senior Frontend Developer',
      type: 'job',
      status: 'published',
      category: 'IT & Technology',
      categories: ['IT & Technology'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 4567,
      comments: 23,
      publishDate: '2024-12-01 08:00:00',
      updatedDate: '2024-12-01 08:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=250&fit=crop',
      excerpt: 'Tuyển Senior Frontend Developer với lương hấp dẫn',
      content: '<p>Chúng tôi đang tìm kiếm Senior Frontend Developer tài năng.</p>',
      slug: 'tuyen-dung/senior-frontend-developer',
      tags: ['Tuyển dụng', 'Frontend', 'ReactJS'],
      jobData: {
        position: 'Senior Frontend Developer',
        company: 'Tech Innovation Co.',
        location: 'Hà Nội / Remote',
        salary: '25-35 triệu VNĐ',
        employmentType: 'Full-time',
        experienceLevel: 'Senior',
        deadline: '2025-01-15 23:59:59',
        requirements: ['5+ years React', 'TypeScript', 'Team lead experience'],
        benefits: ['Competitive salary', 'Remote work', 'Health insurance'],
        contactEmail: 'hr@techinnovation.com',
      },
    },

    // INFOGRAPHIC ARTICLES (User 3)
    {
      id: 11,
      title: 'Infographic: Thống kê thị trường công nghệ 2024',
      type: 'infographic',
      status: 'published',
      category: 'Thống kê',
      categories: ['Thống kê'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 6789,
      comments: 123,
      publishDate: '2024-12-08 10:00:00',
      updatedDate: '2024-12-08 10:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
      excerpt: 'Tổng hợp số liệu thị trường công nghệ Việt Nam năm 2024',
      content: '<p>Infographic với đầy đủ số liệu và biểu đồ.</p>',
      slug: 'infographic/thong-ke-thi-truong-cong-nghe-2024',
      tags: ['Infographic', 'Thống kê', 'Công nghệ'],
      infographicData: {
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200',
        width: 1200,
        height: 3600,
        dataSource: 'Vietnam Tech Report 2024',
      },
    },

    // LEGAL ARTICLES (User 3)
    {
      id: 12,
      title: 'Luật Lao động 2024: Những điểm mới cần biết',
      type: 'legal',
      status: 'published',
      category: 'Luật lao động',
      categories: ['Luật lao động'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 3456,
      comments: 45,
      publishDate: '2024-12-03 09:00:00',
      updatedDate: '2024-12-03 09:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=250&fit=crop',
      excerpt: 'Tổng hợp các điểm mới trong Luật Lao động có hiệu lực từ 2024',
      content: '<p>Luật Lao động 2024 có nhiều thay đổi quan trọng.</p>',
      slug: 'luat-lao-dong/luat-lao-dong-2024-nhung-diem-moi',
      tags: ['Luật', 'Lao động', 'Pháp luật'],
      legalData: {
        documentNumber: '45/2023/QH15',
        issueDate: '2023-11-25',
        effectiveDate: '2024-01-01',
        issuingAuthority: 'Quốc hội',
        documentType: 'Luật',
        status: 'Có hiệu lực',
      },
    },

    // DOWNLOAD ARTICLES (User 3)
    {
      id: 13,
      title: 'Tài liệu: Hướng dẫn sử dụng CMS Platform',
      type: 'download',
      status: 'published',
      category: 'Tài liệu',
      categories: ['Tài liệu'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 2345,
      comments: 34,
      publishDate: '2024-12-06 10:00:00',
      updatedDate: '2024-12-06 10:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=400&h=250&fit=crop',
      excerpt: 'Tài liệu hướng dẫn chi tiết về cách sử dụng CMS Platform',
      content: '<p>Tài liệu đầy đủ với screenshots và ví dụ.</p>',
      slug: 'tai-lieu/huong-dan-su-dung-cms-platform',
      tags: ['Tài liệu', 'CMS', 'Hướng dẫn'],
      downloadData: {
        fileUrl: 'https://example.com/cms-user-guide.pdf',
        fileName: 'cms-user-guide.pdf',
        fileSize: '5.2 MB',
        fileType: 'PDF',
        version: '1.0',
        downloadCount: 567,
      },
    },

    // STAFF ARTICLES (User 3)
    {
      id: 14,
      title: 'Giới thiệu: Ông Nguyễn Văn A - Giám đốc Công nghệ',
      type: 'staff',
      status: 'published',
      category: 'Ban lãnh đạo',
      categories: ['Ban lãnh đạo'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 1234,
      comments: 12,
      publishDate: '2024-12-02 10:00:00',
      updatedDate: '2024-12-02 10:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=250&fit=crop',
      excerpt: 'Hồ sơ của Giám đốc Công nghệ với 15 năm kinh nghiệm',
      content: '<p>Ông Nguyễn Văn A là một lãnh đạo tài năng trong ngành công nghệ.</p>',
      slug: 'nhan-su/giam-doc-cong-nghe-nguyen-van-a',
      tags: ['Nhân sự', 'Lãnh đạo', 'Công nghệ'],
      staffData: {
        fullName: 'Nguyễn Văn A',
        position: 'Giám đốc Công nghệ',
        department: 'Công nghệ',
        email: 'nguyenvana@company.com',
        phone: '024 1234 5678',
        bio: 'Hơn 15 năm kinh nghiệm trong lĩnh vực công nghệ thông tin',
        education: ['Thạc sĩ Khoa học Máy tính - MIT', 'Cử nhân CNTT - ĐHBK HN'],
        certifications: ['AWS Certified Solutions Architect', 'PMP'],
      },
    },

    // FAQ ARTICLES (User 3)
    {
      id: 15,
      title: 'Câu hỏi thường gặp về CMS Platform',
      type: 'faq',
      status: 'published',
      category: 'Hỏi đáp',
      categories: ['Hỏi đáp'],
      author: 'Lê Văn C',
      authorId: 3,
      views: 3456,
      comments: 78,
      publishDate: '2024-12-07 10:00:00',
      updatedDate: '2024-12-07 10:00:00',
      thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=250&fit=crop',
      excerpt: 'Tổng hợp các câu hỏi thường gặp về CMS Platform',
      content: '<p>Danh sách câu hỏi và câu trả lời chi tiết.</p>',
      slug: 'hoi-dap/cau-hoi-thuong-gap-ve-cms-platform',
      tags: ['FAQ', 'CMS', 'Hỏi đáp'],
      faqData: {
        questions: [
          {
            question: 'CMS Platform hỗ trợ những tính năng gì?',
            answer: 'CMS Platform hỗ trợ quản lý 15 loại bài viết khác nhau...',
          },
          {
            question: 'Làm thế nào để tạo bài viết mới?',
            answer: 'Bạn có thể tạo bài viết mới bằng cách click vào nút "Tạo mới"...',
          },
        ],
      },
    },

    // More articles from other users
    {
      id: 16,
      title: 'Hướng dẫn sử dụng CMS Platform mới',
      type: 'news',
      status: 'published',
      category: 'Thời sự',
      categories: ['Thời sự'],
      author: 'Nguyễn Văn A',
      authorId: 1,
      views: 1234,
      comments: 45,
      publishDate: '2024-12-26 10:30:00',
      updatedDate: '2024-12-26 14:20:00',
      thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop',
      excerpt: 'Hướng dẫn chi tiết về cách sử dụng CMS Platform cho người mới bắt đầu',
      content: '<p>Đây là hướng dẫn chi tiết về cách sử dụng CMS Platform mới.</p>',
      featured: true,
      wordCount: 1200,
      slug: 'thoi-su/huong-dan-su-dung-cms-platform-moi',
      tags: ['CMS', 'Tutorial', 'Công nghệ'],
    },
    {
      id: 17,
      title: 'Video hướng dẫn thiết kế giao diện Modern',
      type: 'video',
      status: 'published',
      category: 'Phóng sự',
      categories: ['Phóng sự'],
      author: 'Trần Thị B',
      authorId: 2,
      views: 2340,
      comments: 67,
      publishDate: '2024-12-25 14:00:00',
      updatedDate: '2024-12-25 16:30:00',
      thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=250&fit=crop',
      excerpt: 'Học cách thiết kế giao diện hiện đại với Figma và Tailwind CSS',
      content: '<p>Video hướng dẫn chi tiết về thiết kế giao diện.</p>',
      slug: 'phong-su/video-huong-dan-thiet-ke-giao-dien-modern',
      tags: ['Design', 'Figma', 'Tailwind'],
      videoData: {
        sourceType: 'youtube',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        duration: { hours: 0, minutes: 15, seconds: 30 },
        thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=250&fit=crop',
        quality: '1080p',
        summary: 'Video hướng dẫn chi tiết về thiết kế giao diện modern',
      },
    },
  ];

  console.log('Seeding articles...');
  
  for (const article of sampleArticles) {
    await kv.set(`article:${article.id}`, article);
    console.log(`✓ Seeded article: ${article.title}`);
  }
  
  console.log(`✅ Successfully seeded ${sampleArticles.length} articles`);
}
